on: [push]
name: Build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install toolchain
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --verbose
